-- =============================================
-- AlSa3d Accounting System - Database Setup
-- إنشاء قاعدة البيانات
-- =============================================
-- التاريخ: 2026
-- الإصدار: 1.0
-- =============================================

USE master;
GO

-- حذف قاعدة البيانات إذا كانت موجودة (لأغراض التطوير)
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'AlSa3d')
BEGIN
    ALTER DATABASE [AlSa3d] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [AlSa3d];
END
GO

-- إنشاء قاعدة البيانات
CREATE DATABASE [AlSa3d]
CONTAINMENT = NONE
ON PRIMARY 
(
    NAME = N'AlSa3d_Data',
    FILENAME = N'C:\SQLData\AlSa3d_Data.mdf',
    SIZE = 512MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 128MB
)
LOG ON 
(
    NAME = N'AlSa3d_Log',
    FILENAME = N'C:\SQLData\AlSa3d_Log.ldf',
    SIZE = 128MB,
    MAXSIZE = 2048GB,
    FILEGROWTH = 64MB
)
COLLATE Arabic_CI_AS_KS_WS;
GO

-- إعدادات قاعدة البيانات
ALTER DATABASE [AlSa3d] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [AlSa3d] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [AlSa3d] SET ANSI_NULLS OFF;
ALTER DATABASE [AlSa3d] SET ANSI_PADDING OFF;
ALTER DATABASE [AlSa3d] SET ANSI_WARNINGS OFF;
ALTER DATABASE [AlSa3d] SET ARITHABORT OFF;
ALTER DATABASE [AlSa3d] SET AUTO_CLOSE OFF;
ALTER DATABASE [AlSa3d] SET AUTO_SHRINK OFF;
ALTER DATABASE [AlSa3d] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [AlSa3d] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [AlSa3d] SET CURSOR_DEFAULT GLOBAL;
ALTER DATABASE [AlSa3d] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [AlSa3d] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [AlSa3d] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [AlSa3d] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [AlSa3d] SET DISABLE_BROKER;
ALTER DATABASE [AlSa3d] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE [AlSa3d] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [AlSa3d] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [AlSa3d] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [AlSa3d] SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE [AlSa3d] SET RECOVERY FULL;
ALTER DATABASE [AlSa3d] SET MULTI_USER;
ALTER DATABASE [AlSa3d] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [AlSa3d] SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE [AlSa3d] SET DELAYED_DURABILITY = DISABLED;
GO

-- تم إنشاء قاعدة البيانات بنجاح
PRINT '✓ تم إنشاء قاعدة البيانات AlSa3d بنجاح';
PRINT '✓ المسار: C:\SQLData\AlSa3d_Data.mdf';
PRINT '✓ Collation: Arabic_CI_AS_KS_WS';
GO
